spring:
  application:
    name: reviews
  datasource:
    url: jdbc:mysql://localhost:3306/universal_reviews
    username: application_user
    password: Abcd@123

server:
  port: 8083

okta:
  oauth2:
    issuer: https://dev-70557799.okta.com/oauth2/default
    audience: api://default

